FORMAT: 1A
HOST: https://api.wysker.com/v8/

# wysker API

<!-- include(oauth.apib) -->
<!-- include(users.apib) -->
<!-- include(friends.apib) -->
<!-- include(favorites.apib) -->
<!-- include(countries.apib) -->
<!-- include(currencies.apib) -->
<!-- include(channels.apib) -->
<!-- include(reactions.apib) -->
<!-- include(nodes.apib) -->
<!-- include(tokens.apib) -->
<!-- include(structures.apib) -->