FORMAT: 1A
HOST: https://api.wysker.com/v12/

# wysker API

<!-- include(accounts.apib) -->
<!-- include(channels.apib) -->
<!-- include(countries.apib) -->
<!-- include(currencies.apib) -->
<!-- include(favorites.apib) -->
<!-- include(feed.apib) -->
<!-- include(friends.apib) -->
<!-- include(nodes.apib) -->
<!-- include(notifications.apib) -->
<!-- include(oauth.apib) -->
<!-- include(radio.apib) -->
<!-- include(reactions.apib) -->
<!-- include(search.apib) -->
<!-- include(tokens.apib) -->
<!-- include(users.apib) -->
<!-- include(widgets.apib) -->

<!-- include(structures.apib) -->